// blank_system.go — Replace opencode's built-in default system prompt with
// foci's per-session prompt.
//
// opencode injects its own default system prompt ("You are opencode, an
// interactive CLI tool…") into every session. We want ONLY foci's character
// prompt to reach the model. A named agent with a minimal (" ") prompt does
// NOT suppress the default — verified against opencode 1.17.15 by capturing
// the outgoing provider request, the default was still present (and requesting
// an unregistered "foci" agent jammed every opencode agent, 2026-07-08).
//
// Instead a plugin using the experimental.chat.system.transform hook rewrites
// the assembled system array right before the request is built: it reads foci's
// prompt for the CALLING session from a per-session file and sets
// output.system = [that prompt], dropping opencode's default.
//
// Why a per-session FILE (not baked into the plugin, not a live foci RPC):
// one `opencode serve` is shared across ALL of an agent's sessions and loads
// the plugin ONCE at boot — so the prompt can't be baked in (it varies per
// session via the platform env block, and changes on reload). The prompt is
// static between session Starts, so a live foci call every turn would be wasted
// work; foci writes the file once per Start and the plugin reads it locally
// each turn. This mirrors the session-env plugin (session_env.go) exactly.
//
// foci also still sends its prompt in the POST "system" field: that's the
// fallback if the file is ever missing (write failed) — the session keeps a
// prompt rather than running naked. When the file is present the plugin
// replaces the whole array, so there's no doubling.

package opencode

import (
	"os"
	"path/filepath"
	"strings"

	"foci/internal/log"
	"foci/internal/tempdir"
)

const (
	sessionSystemSubdir = "session-system"  // under tempdir
	blankSystemPluginFn = "blank-system.ts" // under .opencode/plugin/
)

// sessionSystemDir returns the tempdir subdirectory for per-session
// system-prompt files.
func sessionSystemDir() string {
	return filepath.Join(tempdir.Dir(), sessionSystemSubdir)
}

// sessionSystemPath returns the system-prompt file path for one opencode session.
func sessionSystemPath(sessionID string) string {
	return filepath.Join(sessionSystemDir(), sessionID)
}

// WriteSessionSystemFile writes foci's resolved system prompt for a session to
// the file the blank-system plugin reads. Called at Start (create / resume /
// compaction-bounce) — exactly when the prompt is (re)resolved from disk.
// Best-effort: errors are logged but do not fail Start (the plugin then leaves
// opencode's default in place, and foci's "system" POST field is the fallback).
func WriteSessionSystemFile(sessionID, prompt string) {
	if sessionID == "" || prompt == "" {
		return
	}
	dir := sessionSystemDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Warnf("opencode", "session-system: mkdir %s: %v", dir, err)
		return
	}
	if err := os.WriteFile(sessionSystemPath(sessionID), []byte(prompt), 0o644); err != nil {
		log.Warnf("opencode", "session-system: write %s: %v", sessionID, err)
		return
	}
	log.Debugf("opencode", "session-system: wrote prompt for session %s (%d bytes)", sessionID, len(prompt))
}

// RemoveSessionSystemFile removes the per-session system-prompt file. Best-effort.
func RemoveSessionSystemFile(sessionID string) {
	if sessionID == "" {
		return
	}
	_ = os.Remove(sessionSystemPath(sessionID))
}

// EnsureBlankSystemPlugin writes the system-prompt plugin into the agent
// workspace if missing or stale. Must run BEFORE the server is acquired
// (opencode loads plugins at subprocess startup). Idempotent and best-effort.
func EnsureBlankSystemPlugin(workDir string) {
	ensureWorkspacePlugin(workDir, blankSystemPluginFn, blankSystemPluginSource(sessionSystemDir()))
}

// blankSystemPluginSource returns the TypeScript source for the system-prompt
// plugin, templated with the per-session prompt-file directory so the plugin
// has no runtime dependency on opencode's environment. The hook reads
// <dir>/<sessionID>; if present it replaces the whole system array with that
// prompt (dropping opencode's default), else it leaves the array untouched so
// the session still has a prompt (foci's "system" field).
func blankSystemPluginSource(sysDir string) string {
	const tmpl = `// Auto-generated by foci. Replaces opencode's built-in default system
// prompt ("You are opencode…") with foci's per-session prompt, read from a
// file foci writes at session start. Do not edit; foci rewrites this on
// session start.
export default function() {
  const sysDir = {{SYS_DIR}};
  return {
    "experimental.chat.system.transform": async (input, output) => {
      try {
        if (!input || !input.sessionID) return;
        const f = Bun.file(sysDir + "/" + input.sessionID);
        if (await f.exists()) {
          const prompt = await f.text();
          output.system.length = 0;
          output.system.push(prompt);
        }
      } catch (e) {}
    }
  };
}
`
	return strings.ReplaceAll(tmpl, "{{SYS_DIR}}", "`"+sysDir+"`")
}
