// session_env.go — Per-session exec-bridge env routing for the shared
// opencode server model.
//
// PROBLEM: opencode runs ONE 'opencode serve' subprocess per agent, shared
// across all sessions. The subprocess's env (FOCI_SOCK, BASH_ENV) is
// captured from the first session that launched it and frozen — so every
// subsequent session's bash tool calls go through the FIRST session's exec
// bridge socket. Session-scoped tools (foci_ask, send_to_session) then
// route to the wrong chat.
//
// FIX: opencode fires a `shell.env` plugin hook before every bash spawn,
// passing the calling session's ID. A foci-generated plugin (.opencode/plugin/)
// reads a per-session JSON file written by this code and injects the correct
// FOCI_SOCK/BASH_ENV, overriding the subprocess default. Each session gets
// its own mapping file in tempdir; the plugin reads it on every spawn.

package opencode

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"

	"foci/internal/log"
	"foci/internal/tempdir"
)

const (
	sessionEnvSubdir   = "session-env"         // under tempdir
	sessionEnvPluginFn = "foci-session-env.ts" // under .opencode/plugin/
)

// sessionEnvEntry is the JSON the plugin reads. Only the bridge env vars
// that differ per-session are included; everything else inherits from the
// subprocess env.
type sessionEnvEntry struct {
	FociSock string `json:"FOCI_SOCK,omitempty"`
	BashEnv  string `json:"BASH_ENV,omitempty"`
}

// sessionEnvDir returns the tempdir subdirectory for per-session env files.
func sessionEnvDir() string {
	return filepath.Join(tempdir.Dir(), sessionEnvSubdir)
}

// sessionEnvPath returns the env file path for one opencode session.
func sessionEnvPath(sessionID string) string {
	return filepath.Join(sessionEnvDir(), sessionID+".json")
}

// WriteSessionEnvFile writes the per-session env mapping that the opencode
// plugin reads on every bash spawn. Best-effort: errors are logged but do
// not fail Start (the fallback is the existing shared-subprocess env —
// wrong session, but functional).
func WriteSessionEnvFile(sessionID string, env map[string]string) {
	if sessionID == "" {
		return
	}
	entry := sessionEnvEntry{
		FociSock: env["FOCI_SOCK"],
		BashEnv:  env["BASH_ENV"],
	}
	if entry.FociSock == "" && entry.BashEnv == "" {
		return // no bridge env to inject
	}
	dir := sessionEnvDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Warnf("opencode", "session-env: mkdir %s: %v", dir, err)
		return
	}
	data, err := json.Marshal(entry)
	if err != nil {
		log.Warnf("opencode", "session-env: marshal: %v", err)
		return
	}
	if err := os.WriteFile(sessionEnvPath(sessionID), data, 0o644); err != nil {
		log.Warnf("opencode", "session-env: write %s: %v", sessionID, err)
	}
	log.Debugf("opencode", "session-env: wrote mapping for session %s (sock=%s)", sessionID, entry.FociSock)
}

// RemoveSessionEnvFile removes the per-session env mapping. Best-effort.
func RemoveSessionEnvFile(sessionID string) {
	if sessionID == "" {
		return
	}
	_ = os.Remove(sessionEnvPath(sessionID))
}

// sessionEnvPluginPath returns the path to the generated plugin file in
// the agent's workspace.
func sessionEnvPluginPath(workDir string) string {
	return filepath.Join(workDir, ".opencode", "plugin", sessionEnvPluginFn)
}

// EnsureSessionEnvPlugin writes the shell.env plugin file into the workspace
// if it doesn't exist or has stale content. The plugin reads per-session
// env files from tempdir and injects them into every bash spawn, overriding
// the shared subprocess's first-session-pinned FOCI_SOCK/BASH_ENV.
//
// The tempdir path is templated in at generation time so the plugin has no
// runtime dependency on opencode's input API or environment. Uses Bun.file
// for fast cached reads on every bash spawn.
func EnsureSessionEnvPlugin(workDir string) {
	if workDir == "" {
		return
	}
	envDir := sessionEnvDir()
	want := sessionEnvPluginSource(envDir)

	path := sessionEnvPluginPath(workDir)
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Warnf("opencode", "session-env: mkdir plugin %s: %v", dir, err)
		return
	}

	// Skip write if content is already current (avoids touching mtime on
	// every session start, which could trigger file-watchers).
	if existing, err := os.ReadFile(path); err == nil && string(existing) == want {
		return
	}
	if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
		log.Warnf("opencode", "session-env: write plugin: %v", err)
		return
	}
	log.Debugf("opencode", "session-env: wrote plugin to %s", path)
}

// sessionEnvPluginSource returns the TypeScript source for the shell.env
// plugin, templated with the resolved env-file directory.
func sessionEnvPluginSource(envDir string) string {
	const tmpl = `// Auto-generated by foci. Per-session FOCI_SOCK/BASH_ENV routing for
// opencode's shared-server model. Without this, all sessions inherit the
// first session's bridge socket, misrouting session-scoped exec-bridge tools
// (foci_ask, send_to_session). Do not edit; foci rewrites this on session start.
export default function() {
  const envDir = {{ENV_DIR}};
  return {
    "shell.env": async (evt, output) => {
      if (!evt.sessionID) return;
      try {
        const f = Bun.file(envDir + "/" + evt.sessionID + ".json");
        if (await f.exists()) {
          Object.assign(output.env, await f.json());
        }
      } catch (e) {}
    }
  };
}
`
	return strings.ReplaceAll(tmpl, "{{ENV_DIR}}", "`"+envDir+"`")
}
