// session_env.go — opencode's half of the per-session exec-bridge env routing
// described in internal/delegator/sessionenv.
//
// PROBLEM: opencode runs ONE 'opencode serve' subprocess per agent, shared
// across all sessions. The subprocess's env (FOCI_SOCK, BASH_ENV,
// FOCI_SESSION_KEY) is captured from the first session that launched it and
// frozen — so every subsequent session's bash tool calls go through the
// FIRST session's exec bridge socket (and see the FIRST session's key).
// Session-scoped tools (foci_ask, send_to_session) then route to the wrong
// chat.
//
// FIX: opencode fires a `shell.env` plugin hook before every bash spawn,
// passing the calling session's ID. A foci-generated plugin (.opencode/plugin/)
// reads the per-session JSON file the sessionenv package writes and injects
// the correct FOCI_SOCK/BASH_ENV/FOCI_SESSION_KEY, overriding the subprocess
// default. Each session gets its own mapping file in tempdir; the plugin reads
// it on every spawn.
//
// The file format, its location and its lifecycle are shared with the codex
// backend (which cannot set a spawn env at all and has to rewrite the command
// instead) — only the injector below is opencode-specific.

package opencode

import (
	"path/filepath"
	"strings"

	"foci/internal/delegator/sessionenv"
)

const sessionEnvPluginFn = "foci-session-env.ts" // under .opencode/plugin/

// WriteSessionEnvFile writes the per-session env mapping that the opencode
// plugin reads on every bash spawn. Best-effort: errors are logged but do
// not fail Start (the fallback is the existing shared-subprocess env —
// wrong session, but functional).
func WriteSessionEnvFile(sessionID string, env map[string]string) {
	if err := sessionenv.Write(sessionID, env); err != nil {
		opencodeLog.Warnf("session-env: %v", err)
		return
	}
	opencodeLog.Debugf("session-env: wrote mapping for session %s", sessionID)
}

// RemoveSessionEnvFile removes the per-session env mapping. Best-effort.
func RemoveSessionEnvFile(sessionID string) {
	if err := sessionenv.Remove(sessionID); err != nil {
		opencodeLog.Debugf("session-env: %v", err)
	}
}

// EnsureSessionEnvPlugin writes the shell.env plugin file into the workspace
// if it doesn't exist or has stale content. The plugin reads per-session
// env files from tempdir and injects them into every bash spawn, overriding
// the shared subprocess's first-session-pinned FOCI_SOCK/BASH_ENV.
//
// The tempdir path is templated in at generation time so the plugin has no
// runtime dependency on opencode's input API or environment. Uses Bun.file
// for fast cached reads on every bash spawn.
func EnsureSessionEnvPlugin(workDir string) {
	if workDir == "" {
		return
	}
	ensureWorkspacePlugin(workDir, sessionEnvPluginFn, sessionEnvPluginSource(sessionenv.Dir()))
}

// ensureWorkspacePlugin writes a foci-generated plugin file into the agent
// workspace's .opencode/plugin/ dir if it's missing or its content is stale.
// Shared by every foci opencode plugin (session-env, blank-system). Idempotent:
// skips the write when content already matches (avoids touching mtime on every
// session start, which could trigger file-watchers). Best-effort — errors are
// logged, never fatal. Must run BEFORE the server is acquired: opencode loads
// plugins at subprocess startup.
func ensureWorkspacePlugin(workDir, filename, content string) {
	if workDir == "" {
		return
	}
	path := filepath.Join(workDir, ".opencode", "plugin", filename)
	wrote, err := sessionenv.EnsureFile(path, content, 0o644)
	if err != nil {
		opencodeLog.Warnf("plugin: %v", err)
		return
	}
	if wrote {
		opencodeLog.Debugf("plugin: wrote %s", path)
	}
}

// sessionEnvPluginSource returns the TypeScript source for the shell.env
// plugin, templated with the resolved env-file directory.
func sessionEnvPluginSource(envDir string) string {
	const tmpl = `// Auto-generated by foci. Per-session FOCI_SOCK/BASH_ENV routing for
// opencode's shared-server model. Without this, all sessions inherit the
// first session's bridge socket, misrouting session-scoped exec-bridge tools
// (foci_ask, send_to_session). Do not edit; foci rewrites this on session start.
export default function() {
  const envDir = {{ENV_DIR}};
  return {
    "shell.env": async (evt, output) => {
      if (!evt.sessionID) return;
      try {
        const f = Bun.file(envDir + "/" + evt.sessionID + ".json");
        if (await f.exists()) {
          Object.assign(output.env, await f.json());
        }
      } catch (e) {}
    }
  };
}
`
	return strings.ReplaceAll(tmpl, "{{ENV_DIR}}", "`"+envDir+"`")
}
