package testharness

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// testConfigOpts collects parameters for writing a synthetic foci.toml
// for L2 integration tests. The values are picked so foci-gw can start
// without hitting any real external service:
//   - api_base points at the in-process Telegram stub
//   - claude_binary points at the cc-stub
//   - Anthropic keys are stub strings (no real API calls made by cc-stub)
//   - data/logs dirs are under t.TempDir()
type testConfigOpts struct {
	DataDir         string
	LogsDir         string
	ClaudeBinary    string
	TelegramBase    string
	SecretsPath     string
	Agents          []AgentSpec
	Workspaces      map[string]string // agent id → workspace path
	RecorderPath    string
	HTTPPort        int    // kernel-assigned ephemeral port; 0 falls back to foci's default 18791 (collides under t.Parallel)
	ExtraConfigTOML string // appended verbatim at the end of the config
}

// writeTestConfig writes a minimal foci.toml at path. The config defines
// one model (haiku, never actually called because cc-stub doesn't reach
// the API), and one [[agents]] entry per spec wired up with a
// claude-code backend pointed at the cc-stub.
func writeTestConfig(t *testing.T, path string, o testConfigOpts) {
	t.Helper()
	var sb strings.Builder
	fmt.Fprintf(&sb, `# Auto-generated by internal/testharness/gateway.go for an L2 integration test.
# Not for production use.

data_dir = %q
skip_security_checks = true
welcome_file = %q
`, o.DataDir, filepath.Join(o.DataDir, "WELCOME.md"))
	// welcome_file: scope to test DataDir. The default "data/WELCOME.md"
	// resolves via ResolvePath to $HOME/data/WELCOME.md (e.g.
	// /home/foci/data/WELCOME.md). readAndConsumeWelcomeFile in foci-gw
	// reads the file then DELETES it. Without an override, any test that
	// boots after a foci update has staged a welcome file would race-
	// consume + delete that file before production foci ever shows it.
	// Scoping to the test's DataDir means each test gets its own (never-
	// written) welcome path, so the consume-and-delete is a safe no-op.

	// Override the HTTP port so parallel tests don't all collide on the
	// hardcoded default (127.0.0.1:18791). The harness picks an ephemeral
	// port via the kernel before we get here; if HTTPPort is zero we skip
	// the override and let foci's default apply.
	if o.HTTPPort > 0 {
		fmt.Fprintf(&sb, `
[http]
port = %d
`, o.HTTPPort)
	}

	// Emit [logging] only if the test isn't supplying its own. Tests that
	// need to override event_file / log_rotation / etc. inject a full
	// [logging] section via ExtraConfigTOML; strict TOML parsers reject
	// duplicate table definitions, so we skip the base emission in that
	// case. Match exact `[logging]` headers (not `[logging.subsection]`).
	//
	// IMPORTANT: scope all log paths to the test's LogsDir. The defaults for
	// api_file ("logs/api.jsonl") and payload_file ("logs/api-payload.jsonl")
	// are relative paths that ResolvePath joins against $HOME — without an
	// override, every test foci-gw writes (and at startup ROTATES) the host
	// user's production logs. Concurrent tests then race the same shared
	// files. Same hazard for archive_dir (which otherwise defaults to
	// EventFile's parent + "/archive"). Tests that need to disable a
	// specific log file should set its key to "" via ExtraConfigTOML.
	if !extraConfigHasSection(o.ExtraConfigTOML, "logging") {
		fmt.Fprintf(&sb, `
[logging]
event_file = %q
api_file = %q
payload_file = %q
archive_dir = %q
`,
			filepath.Join(o.LogsDir, "foci.log"),
			filepath.Join(o.LogsDir, "api.jsonl"),
			filepath.Join(o.LogsDir, "api-payload.jsonl"),
			filepath.Join(o.LogsDir, "archive"),
		)
	}

	fmt.Fprintf(&sb, `
[groups]
powerful = "stub"

[models.stub]
model = "anthropic/claude-haiku-4-5-20251001"

[cc_backend]
claude_binary = %q

[[platforms]]
id = "telegram"
[platforms.access]
allowed_users_only = false
[platforms.telegram]
api_base = %q
long_poll_timeout = "1s"
`, o.ClaudeBinary, o.TelegramBase)

	for _, a := range o.Agents {
		fmt.Fprintf(&sb, `
[[agents]]
id = %q
workspace = %q
backend = "claude-code"

[agents.backend_config]
model = "stub"
`,
			a.ID, o.Workspaces[a.ID],
		)
		// Per-agent backend_config.env only emitted when the spec
		// supplies env vars. Use INLINE-TABLE form ("env = {K=V, ...}")
		// rather than a [agents.backend_config.env] sub-section: foci's
		// BurntSushi/toml decoder reports sub-table keys under a
		// map[string]any field as "unknown" (logged at WARN), even
		// though the values are decoded correctly. The inline form
		// goes through a single decode of the map[string]any value
		// and avoids the warning.
		//
		// Keys are sorted so test snapshots stay stable. Values always
		// emit as quoted strings (foci's backendConfigEnv coerces to
		// whatever Go type the test needs at consumption time).
		if len(a.ExtraEnv) > 0 {
			keys := make([]string, 0, len(a.ExtraEnv))
			for k := range a.ExtraEnv {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			sb.WriteString("env = {")
			for i, k := range keys {
				if i > 0 {
					sb.WriteString(", ")
				}
				fmt.Fprintf(&sb, "%s = %q", k, a.ExtraEnv[k])
			}
			sb.WriteString("}\n")
		}

		// Per-agent [agents.permissions] only emitted when at least one
		// permission knob is set — keeps the generated config minimal
		// for the common case.
		if len(a.AutoApprove) > 0 || a.AutoApproveCommonReadonly != nil || a.AutoApproveCommonSafeWrite != nil {
			sb.WriteString("\n[agents.permissions]\n")
			if len(a.AutoApprove) > 0 {
				sb.WriteString("auto_approve = [")
				for i, rule := range a.AutoApprove {
					if i > 0 {
						sb.WriteString(", ")
					}
					fmt.Fprintf(&sb, "%q", rule)
				}
				sb.WriteString("]\n")
			}
			if a.AutoApproveCommonReadonly != nil {
				fmt.Fprintf(&sb, "auto_approve_common_readonly = %v\n", *a.AutoApproveCommonReadonly)
			}
			if a.AutoApproveCommonSafeWrite != nil {
				fmt.Fprintf(&sb, "auto_approve_common_safe_write = %v\n", *a.AutoApproveCommonSafeWrite)
			}
		}
		fmt.Fprintf(&sb, `
[[agents.platforms]]
id = "telegram"
bot = %q
[agents.platforms.access]
allowed_users = [%q]
`,
			a.ID,
			fmt.Sprintf("%d", a.UserID),
		)
	}

	// Append any test-supplied extra TOML last so it can override
	// preceding keys (TOML's last-wins semantics within a duplicate
	// table) or add unrelated sections wholesale.
	if o.ExtraConfigTOML != "" {
		if !strings.HasPrefix(o.ExtraConfigTOML, "\n") {
			sb.WriteString("\n")
		}
		sb.WriteString(o.ExtraConfigTOML)
		if !strings.HasSuffix(o.ExtraConfigTOML, "\n") {
			sb.WriteString("\n")
		}
	}

	if err := os.WriteFile(path, []byte(sb.String()), 0o600); err != nil {
		t.Fatalf("write test config: %v", err)
	}
}

// extraConfigHasSection reports whether extra contains a top-level
// `[name]` table header. Matches `[logging]` but not `[logging.subkey]`,
// `[logging-other]`, or `[ logging ]` (leading whitespace is non-canonical
// in TOML). Tolerant of CR-LF, leading/trailing whitespace on the line,
// and the header appearing as the first character of the string.
func extraConfigHasSection(extra, name string) bool {
	if extra == "" {
		return false
	}
	header := "[" + name + "]"
	for _, line := range strings.Split(extra, "\n") {
		line = strings.TrimSpace(line)
		if line == header {
			return true
		}
	}
	return false
}

// writeTestSecrets writes a minimal secrets.toml mapping telegram.<bot>
// secrets to the synthetic tokens registered with the Telegram stub.
// Anthropic / OpenAI keys are placeholder values — cc-stub never makes
// real API calls so any non-empty string suffices for foci's startup
// checks (skip_security_checks=true in the config relaxes those further).
//
// extraTOML, if non-empty, is appended verbatim after the generated
// sections. Use to inject custom secret sections (e.g. [custom]
// my_key = "...") for tests exercising {{secret:...}} template
// resolution from arbitrary sources.
func writeTestSecrets(t *testing.T, path string, agents []AgentSpec, extraTOML string) {
	t.Helper()
	var sb strings.Builder
	sb.WriteString("# Auto-generated test secrets — not real credentials.\n\n")
	sb.WriteString("[anthropic]\napi_key = \"sk-test-stub\"\n\n")
	sb.WriteString("[telegram]\n")
	for _, a := range agents {
		fmt.Fprintf(&sb, "%s = %q\n", a.ID, a.BotToken)
	}
	if extraTOML != "" {
		if !strings.HasPrefix(extraTOML, "\n") {
			sb.WriteString("\n")
		}
		sb.WriteString(extraTOML)
		if !strings.HasSuffix(extraTOML, "\n") {
			sb.WriteString("\n")
		}
	}
	if err := os.WriteFile(path, []byte(sb.String()), 0o600); err != nil {
		t.Fatalf("write test secrets: %v", err)
	}
}

// writeWorkspaces creates per-agent workspace directories under tempDir
// and returns a map of agent id → workspace path for the config writer.
// Each workspace gets a minimal character/CRAFT.md so foci-gw's startup
// system-file loader doesn't complain about a missing file.
func writeWorkspaces(t *testing.T, tempDir string, agents []AgentSpec) map[string]string {
	t.Helper()
	out := map[string]string{}
	for _, a := range agents {
		ws := filepath.Join(tempDir, "workspaces", a.ID)
		charDir := filepath.Join(ws, "character")
		memDir := filepath.Join(ws, "memory")
		for _, d := range []string{ws, charDir, memDir} {
			if err := os.MkdirAll(d, 0o755); err != nil {
				t.Fatalf("mkdir %s: %v", d, err)
			}
		}
		// Minimal CRAFT.md so the system-file loader has something to read.
		craft := filepath.Join(charDir, "CRAFT.md")
		if err := os.WriteFile(craft, []byte("# CRAFT.md\n\nTest-only workspace.\n"), 0o600); err != nil {
			t.Fatalf("write %s: %v", craft, err)
		}
		out[a.ID] = ws
	}
	return out
}
