package anthropic

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// readCredentialsFile reads and parses the credentials JSON file, returning the
// claudeAiOauth section. Returns error if the file cannot be read or is invalid JSON.
func readCredentialsFile(path string) (map[string]interface{}, error) {
	path = expandHome(path)

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read credentials file: %w", err)
	}

	var root map[string]interface{}
	if err := json.Unmarshal(data, &root); err != nil {
		return nil, fmt.Errorf("parse credentials: %w", err)
	}

	if oauth, ok := root["claudeAiOauth"].(map[string]interface{}); ok {
		return oauth, nil
	}
	return nil, fmt.Errorf("missing claudeAiOauth section")
}

// ReadSetupToken reads the OAuth access token from a Claude Code credentials
// file (typically ~/.claude/.credentials.json). The token is expected to be
// a long-lived (1-year) token generated by `claude setup-token`.
func ReadSetupToken(path string) (string, error) {
	creds, err := readCredentialsFile(path)
	if err != nil {
		return "", err
	}

	token, ok := creds["accessToken"].(string)
	if !ok {
		return "", fmt.Errorf("accessToken not found or not a string")
	}
	return token, nil
}

// ReadCredentials reads the full OAuth credentials from a Claude Code
// credentials file, including refresh token and expiry. Returns the
// access token, refresh token, and expiry (unix milliseconds).
func ReadCredentials(path string) (accessToken, refreshToken string, expiresAt int64, err error) {
	creds, err := readCredentialsFile(path)
	if err != nil {
		return "", "", 0, err
	}

	accessToken, ok := creds["accessToken"].(string)
	if !ok {
		return "", "", 0, fmt.Errorf("accessToken not found or not a string")
	}

	refreshToken, ok = creds["refreshToken"].(string)
	if !ok {
		return "", "", 0, fmt.Errorf("refreshToken not found or not a string")
	}

	// expiresAt is returned as a number in JSON, which unmarshals to float64
	expiresAtNum, ok := creds["expiresAt"].(float64)
	if !ok {
		return "", "", 0, fmt.Errorf("expiresAt not found or not a number")
	}

	return accessToken, refreshToken, int64(expiresAtNum), nil
}

// expandHome resolves ~ to the user's home directory.
func expandHome(path string) string {
	if strings.HasPrefix(path, "~/") {
		home, err := os.UserHomeDir()
		if err != nil {
			return path
		}
		return home + path[1:]
	}
	return path
}
