// Package codex implements an OpenAI Codex CLI backend using the
// `codex app-server` JSON-RPC 2.0 protocol over stdio.
//
// The app-server is a persistent subprocess: foci launches it once, performs
// an initialize handshake, starts a thread, and drives turns via turn/start.
// Events (agent messages, tool calls, approvals) arrive as JSON-RPC
// notifications and server-initiated requests on the same stdout stream.
//
// The app-server connection is pooled like OpenCode's server; each foci
// session gets a Backend facade bound to one Codex thread.
package codex

import (
	"context"
	"os/exec"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"foci/internal/delegator"
	"foci/internal/delegator/autoapprove"
	"foci/internal/log"
	"foci/internal/modelcaps"
)

func init() {
	delegator.Register("codex", newFromConfig, true)
}

func newFromConfig(cfg map[string]any) (delegator.Delegator, error) {
	b := &Backend{}
	b.cfg = cfg
	b.lg = log.NewComponentLogger("codex")
	return b, nil
}

// Backend is the per-foci-session facade over a shared Codex app-server
// connection. The facade owns one thread's turn, approval, callback, and
// metadata state; the shared owner owns the subprocess and JSON-RPC transport.
type Backend struct {
	cfg     map[string]any
	workDir string
	agentID string
	label   string

	lg *log.ComponentLogger

	// Process. These fields belong to the shared app-server owner. A facade
	// has shared pointing at that owner; process() returns the owner.
	cmd    *exec.Cmd
	writer *Writer
	cancel context.CancelFunc
	done   chan struct{}
	shared *Backend

	// State
	mu      sync.Mutex
	running bool
	closing bool
	// facadeClosed makes Close idempotent PER FACADE. sharedPool.refs is a
	// process-level count, so without a per-facade guard a repeated Close on
	// one facade decrements (or, at zero, falsely reports "last") and can tear
	// down an app-server that sibling sessions are still using.
	facadeClosed    bool
	threadID        string
	sessionFilePath string
	threadStatus    threadStatus
	model           string
	launchModel     string
	catalogueModels []string
	readyCh         chan struct{}
	readyOnce       sync.Once
	startOpts       delegator.StartOptions

	// JSON-RPC request/response correlation
	rpcMu      sync.Mutex
	rpcSeq     int64
	pendingRPC map[int64]chan rpcReply

	// Session-scoped delivery callbacks
	sessionEvents atomic.Pointer[delegator.SessionEvents]

	// Turn state
	turnMu       sync.Mutex
	turnActive   bool
	turnID       string // current turn's id, required as turn/steer's expectedTurnId precondition
	turnEvents   *delegator.TurnEvents
	turnResultCh chan *delegator.TurnResult
	turnText     strings.Builder
	turnTools    int
	stashedUsage *delegator.TurnUsage

	// Activity tracking
	lastActivity atomic.Int64

	// Callbacks (set before Start, read-only after)
	permPromptFn     delegator.PermissionPromptFunc
	onSessionReady   func(sessionID string)
	typingFunc       func(typing bool)
	onPromptsCleared func()
	onModelCaps      func(entries map[string]modelcaps.Caps)

	// Approvals
	permMu           sync.Mutex
	pendingPerms     map[int64]*pendingApproval
	autoApproveRules []autoapprove.Rule
	autoApproveEnv   map[string]string // exact environment inherited by Codex

	// Items stashed by ID from item/started, for correlating approval
	// requests with item details (e.g. file paths for fileChange items).
	itemMu    sync.Mutex
	itemCache map[string]itemEnvelope

	// Subagent thread polling
	subagents *subagentTracker

	// Compaction
	compactMu     sync.Mutex
	compactDoneCh chan struct{}

	// Pending control overrides (set by ControlSender, applied on next turn/start)
	pendingModel    string
	pendingEffort   string
	pendingApproval string
	contextWindow   int

	// Voice mode (#1445): EnterVoiceMode saves pendingEffort and forces "low"
	// for the next turn; ExitVoiceMode restores it. voiceModeActive guards a
	// duplicate/mismatched Exit from clobbering pendingEffort.
	voiceModeActive      bool
	voiceModeSavedEffort string

	// Thread name (auto-generated by Codex, surfaced via TurnResult)
	threadName string

	// Explicit foci-session to Codex-thread mappings. A backend can multiplex
	// more than one Codex thread; callers must not infer a target from the
	// thread created most recently.
	threadMapMu    sync.RWMutex
	sessionThreads map[string]string
	threadSessions map[string]string
	threadBackends map[string]*Backend
	batchRuns      map[string]*batchRun
}

var sharedPool = struct {
	sync.Mutex
	servers map[string]*Backend
	refs    map[string]int
}{servers: make(map[string]*Backend), refs: make(map[string]int)}

// process returns the shared app-server owner. Each Backend facade retains
// its own thread/turn/callback state; only transport and RPC correlation are
// shared.
func (b *Backend) process() *Backend {
	if b.shared != nil {
		return b.shared
	}
	return b
}

func (b *Backend) facadeForThread(id string) *Backend {
	p := b.process()
	p.threadMapMu.RLock()
	f := p.threadBackends[id]
	p.threadMapMu.RUnlock()
	return f
}

// processDone returns the shared app-server process's terminal channel,
// closed by onReaderStopped once the process is confirmed gone. A batch's
// deferred cleanup (waiting for a still-live turn to actually finish before
// unregistering its thread, see RunBatch) selects on this too, so a process
// that dies mid-turn can't leak that cleanup goroutine forever.
func (b *Backend) processDone() <-chan struct{} {
	p := b.process()
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.done
}

// pendingApproval tracks an outstanding server-initiated approval request.
type batchRun struct {
	fociSessionID string
	turnID        string
	text          strings.Builder
	done          chan batchResult
	mu            sync.Mutex
}

type batchResult struct {
	text string
	err  error
}

type pendingApproval struct {
	rpcID   int64
	itemID  string
	command string
}

// IsRunning reports whether the Codex app-server subprocess is alive.
func (b *Backend) IsRunning() bool {
	p := b.process()
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.running
}

// IsTurnInFlight reports whether a turn callback is registered but hasn't
// fired yet.
func (b *Backend) IsTurnInFlight() bool {
	b.turnMu.Lock()
	defer b.turnMu.Unlock()
	return b.turnActive
}

// SessionID returns the Codex thread ID.
func (b *Backend) SessionID() string {
	b.mu.Lock()
	key := b.startOpts.SessionKey
	b.mu.Unlock()
	if key == "" {
		return ""
	}
	return b.threadForSession(key)
}

// SessionIDFor resolves a Codex thread for an explicit foci session key.
func (b *Backend) SessionIDFor(fociSessionID string) string {
	b.mu.Lock()
	own := b.startOpts.SessionKey
	b.mu.Unlock()
	if fociSessionID != own {
		return ""
	}
	return b.threadForSession(own)
}

// ConsumeThreadName clears the cached auto-generated thread name once the
// caller has durably applied it (e.g. set as a chat alias). Without this,
// b.threadName — set once by the thread/name/updated notification and
// otherwise never cleared — resurfaces in every subsequent TurnResult,
// making the caller re-run its whole alias read+write path every turn for
// the rest of the session. Implements delegator.ThreadNameConsumer.
func (b *Backend) ConsumeThreadName() {
	b.mu.Lock()
	b.threadName = ""
	b.mu.Unlock()
}

// SessionFilePath returns the on-disk path of this session's transcript,
// reported by Codex in the thread metadata.
func (b *Backend) SessionFilePath() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.sessionFilePath
}

// touchActivity records the current time as the most recent event.
func (b *Backend) touchActivity() {
	b.lastActivity.Store(time.Now().UnixNano())
}

// LastActivity returns the time of the most recent event from Codex.
func (b *Backend) LastActivity() time.Time {
	ns := b.lastActivity.Load()
	if ns == 0 {
		return time.Time{}
	}
	return time.Unix(0, ns)
}

func (b *Backend) threadLogPrefix() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.threadID == "" {
		return "thread=<unknown>"
	}
	return "thread=" + b.threadID
}

func (b *Backend) logDebugf(format string, args ...any) {
	b.lg.Debugf("["+b.threadLogPrefix()+"] "+format, args...)
}

func (b *Backend) logInfof(format string, args ...any) {
	b.lg.Infof("["+b.threadLogPrefix()+"] "+format, args...)
}

func (b *Backend) logWarnf(format string, args ...any) {
	b.lg.Warnf("["+b.threadLogPrefix()+"] "+format, args...)
}

// registerThread records a codex thread's owning foci session and facade, and
// publishes the same mapping to the PreToolUse hook (#1557) via the session-env
// file keyed by thread id.
//
// The two must be written together. They are the same fact — "this thread
// belongs to that session" — seen from foci's side and from a spawned bash's
// side, and a thread that has one without the other runs its shell tools under
// whichever session happened to launch the shared app-server. That was a live
// gap: bindThreadEnv used to be called by hand next to two of this function's
// four call sites, so batch threads (batch.go) and threads first seen via a
// thread/started notification (handlers.go) were registered with no env of
// their own. Keeping the two writes in one place makes the drift impossible
// rather than merely fixed.
func (b *Backend) registerThread(fociSessionID, codexThreadID string) {
	if codexThreadID == "" {
		return
	}
	p := b.process()
	p.threadMapMu.Lock()
	if p.sessionThreads == nil {
		p.sessionThreads = make(map[string]string)
	}
	if p.threadSessions == nil {
		p.threadSessions = make(map[string]string)
	}
	if p.threadBackends == nil {
		p.threadBackends = make(map[string]*Backend)
	}
	if fociSessionID != "" {
		p.sessionThreads[fociSessionID] = codexThreadID
	}
	p.threadSessions[codexThreadID] = fociSessionID
	p.threadBackends[codexThreadID] = b
	p.threadMapMu.Unlock()

	// Outside the map lock: this writes a file, and nothing reads it through
	// threadMapMu.
	b.bindThreadEnv(codexThreadID)
}

func (b *Backend) threadForSession(fociSessionID string) string {
	p := b.process()
	p.threadMapMu.RLock()
	defer p.threadMapMu.RUnlock()
	return p.sessionThreads[fociSessionID]
}

// unregisterThread is registerThread's exact inverse, including the session-env
// file — a facade or batch that closed used to drop its map entries and leave
// the env file behind.
func (b *Backend) unregisterThread(codexThreadID string) {
	p := b.process()
	p.threadMapMu.Lock()
	delete(p.threadSessions, codexThreadID)
	delete(p.threadBackends, codexThreadID)
	for key, id := range p.sessionThreads {
		if id == codexThreadID {
			delete(p.sessionThreads, key)
		}
	}
	p.threadMapMu.Unlock()

	b.unbindThreadEnv(codexThreadID)
}

func (b *Backend) logErrorf(format string, args ...any) {
	b.lg.Errorf("["+b.threadLogPrefix()+"] "+format, args...)
}

func (b *Backend) StatusDetail() string {
	detail := "sandbox=" + b.sandboxMode()
	b.mu.Lock()
	status := b.threadStatus.String()
	b.mu.Unlock()
	if status != "" {
		detail += " | codex=" + status
	}
	return detail
}

func (b *Backend) sandboxMode() string {
	if v, ok := b.cfg["sandbox"].(string); ok && v != "" {
		return v
	}
	return "workspace-write"
}

func (b *Backend) codexBinary() string {
	if v, ok := b.cfg["binary"].(string); ok && v != "" {
		return v
	}
	return "codex"
}

func (b *Backend) WaitForTurn(ctx context.Context) error {
	b.turnMu.Lock()
	ch := b.turnResultCh
	b.turnMu.Unlock()
	if ch == nil {
		return nil
	}
	select {
	case <-ch:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}
