package skills

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

)

// skillLogInterval is how long a skill's load/override/autogenerated log line is
// suppressed after being emitted. A var so tests can shorten it. Set to a day so
// a long-running process re-surfaces autogenerated-skill review reminders daily
// rather than only once per process lifetime.
var skillLogInterval = 24 * time.Hour

// logDeduper suppresses repeated skill load/warn log lines so each distinct
// skill logs at most once per skillLogInterval, process-wide across every load
// path (Load, LoadForAgent) — the registry is rebuilt on every session-context
// assembly, but the model needs the WARNING (esp. "autogenerated, needs human
// review") at most daily, not on every rebuild.
type logDeduper struct {
	mu   sync.Mutex
	seen map[string]time.Time
	now  func() time.Time
}

func newLogDeduper() *logDeduper {
	return &logDeduper{seen: make(map[string]time.Time), now: time.Now}
}

// should reports whether key's log line should be emitted now, stamping the time
// when it returns true. The same key returns false until skillLogInterval has
// elapsed since it last returned true.
func (d *logDeduper) should(key string) bool {
	d.mu.Lock()
	defer d.mu.Unlock()
	now := d.now()
	if last, ok := d.seen[key]; ok && now.Sub(last) < skillLogInterval {
		return false
	}
	d.seen[key] = now
	return true
}

// logDedup is the process-wide skill-log dedup state.
var logDedup = newLogDeduper()

// Skill represents a loaded skill from a SKILL.md file.
type Skill struct {
	Name          string // from frontmatter
	Description   string // from frontmatter
	Command       string // optional slash command (e.g. "/reheat")
	Script        string // optional script path (absolute, resolved from skill dir)
	Dir           string // absolute path to skill directory
	Path          string // absolute path to SKILL.md
	Autogenerated bool   // from frontmatter; true = created by reflection pass, awaiting human review
}

// Registry holds loaded skills.
type Registry struct {
	skills []Skill
}

// Load scans directories for subdirectories containing SKILL.md files,
// parses their YAML frontmatter, and returns a registry.
// Directories are scanned in order; when a skill name appears in multiple
// directories, the later directory wins (overrides the earlier one).
func Load(dirs []string) *Registry {
	r := &Registry{}
	seen := make(map[string]int) // name → index in r.skills
	for _, dir := range dirs {
		mergeInto(r, seen, scanDir(dir))
	}
	return r
}

// scanDir reads a single directory and returns the skills parsed from each
// subdirectory's SKILL.md, in directory order. A missing or unreadable
// directory yields nil (logged at debug, not an error). Per-skill parse
// failures are logged and skipped. scanDir performs no loaded/override
// logging — that belongs to mergeInto, which alone holds the cross-directory
// dedup state needed to tell a fresh load from an override.
func scanDir(dir string) []Skill {
	entries, err := os.ReadDir(dir)
	if err != nil {
		skillsLog.Debugf("scan: %v", err)
		return nil
	}
	var out []Skill
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		skillDir := filepath.Join(dir, entry.Name())
		skillFile := filepath.Join(skillDir, "SKILL.md")
		skill, err := parseSkillFile(skillFile, skillDir)
		if err != nil {
			skillsLog.Warnf("skip %s: %v", skillFile, err)
			continue
		}
		out = append(out, skill)
	}
	return out
}

// mergeInto overlays skills into r, tracking names via seen (name → index in
// r.skills). A skill with a new name is appended and logged (autogenerated →
// warn, otherwise info). A skill whose name already exists overrides the prior
// entry and logs an override line. All loaded/override logging lives here, so
// each skill is logged once per merge rather than once per directory scanned.
func mergeInto(r *Registry, seen map[string]int, skills []Skill) {
	for _, skill := range skills {
		key := skill.Dir + "\x00" + skill.Name + "\x00" + strconv.FormatBool(skill.Autogenerated)
		if idx, exists := seen[skill.Name]; exists {
			if logDedup.should(key) {
				skillsLog.Infof("override: %s (from %s, replacing %s)", skill.Name, skill.Dir, r.skills[idx].Dir)
			}
			r.skills[idx] = skill
			continue
		}
		seen[skill.Name] = len(r.skills)
		r.skills = append(r.skills, skill)
		if skill.Autogenerated {
			if logDedup.should(key) {
				skillsLog.Warnf("loaded: %s (%s) — autogenerated, needs human review", skill.Name, skill.Dir)
			}
		} else if logDedup.should(key) {
			skillsLog.Infof("loaded: %s (%s)", skill.Name, skill.Dir)
		}
	}
}

// Loader builds per-agent skill registries while guaranteeing that a shared
// skills directory is read from disk — and its skills logged/warned about —
// exactly once, regardless of how many agents reference it. Per-agent
// dedicated directories are scanned on every LoadForAgent call, since they
// differ per agent. Use NewLoader; the zero value is not ready.
//
// This exists because foci loads every agent in a startup loop. Calling Load
// per agent re-scanned the shared dir once per agent and emitted N copies of
// each "autogenerated, needs human review" warning — one scan for the shared
// dir, one for each agent's dedicated dir is the intended shape.
type Loader struct {
	mu        sync.Mutex
	shared    map[string][]Skill // sharedDir → skills, scanned once
	scanCount map[string]int     // sharedDir → number of disk scans (observability/tests)
}

// NewLoader returns a ready Loader.
func NewLoader() *Loader {
	return &Loader{
		shared:    make(map[string][]Skill),
		scanCount: make(map[string]int),
	}
}

// scanSharedOnce returns the shared directory's skills, reading disk (and
// logging each skill's loaded/autogenerated line) only on the first call for a
// given dir. Later calls return the cached slice without re-scanning or
// re-logging.
func (l *Loader) scanSharedOnce(sharedDir string) []Skill {
	l.mu.Lock()
	defer l.mu.Unlock()
	if s, ok := l.shared[sharedDir]; ok {
		return s
	}
	r := &Registry{}
	mergeInto(r, make(map[string]int), scanDir(sharedDir))
	l.shared[sharedDir] = r.skills
	l.scanCount[sharedDir]++
	return r.skills
}

// LoadForAgent returns a registry combining the shared directory (scanned and
// logged once across all agents) with the agent's dedicated directory (scanned
// and logged on every call). Agent skills override shared skills of the same
// name, matching Load's later-directory-wins ordering. The cached shared slice
// is copied before overlay, so one agent's override never mutates the shared
// skills seen by another.
func (l *Loader) LoadForAgent(sharedDir, agentDir string) *Registry {
	sharedSkills := l.scanSharedOnce(sharedDir)
	r := &Registry{skills: append([]Skill(nil), sharedSkills...)}
	seen := make(map[string]int, len(r.skills))
	for i, s := range r.skills {
		seen[s.Name] = i
	}
	mergeInto(r, seen, scanDir(agentDir))
	return r
}

// All returns all loaded skills.
func (r *Registry) All() []Skill {
	return r.skills
}

// Len returns the number of loaded skills.
func (r *Registry) Len() int {
	return len(r.skills)
}

// SystemBlock returns a formatted text block listing available skills,
// suitable for injection into the system prompt. Returns empty string
// if no skills are loaded. workDir is the agent's workspace directory;
// if non-empty, skill paths are shown as the shorter of absolute or
// relative-to-workDir.
func (r *Registry) SystemBlock(workDir string) string {
	if len(r.skills) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Available Skills\n\n")
	b.WriteString("Use the read tool to read a skill's SKILL.md for full instructions.\n\n")
	for _, s := range r.skills {
		desc := s.Description
		if s.Autogenerated {
			desc += " [autogenerated — review and refine if used]"
		}
		b.WriteString(fmt.Sprintf("- %s (%s): %s\n", s.Name, shortPath(s.Path, workDir), desc))
	}
	return b.String()
}

// CheckSizes returns warning strings for any skill whose SKILL.md exceeds
// maxChars bytes. Returns nil if maxChars <= 0 (guard disabled) or no skills
// exceed the limit.
func (r *Registry) CheckSizes(maxChars int) []string {
	if maxChars <= 0 {
		return nil
	}
	var warnings []string
	for _, s := range r.skills {
		info, err := os.Stat(s.Path)
		if err != nil {
			continue
		}
		if size := int(info.Size()); size > maxChars {
			warnings = append(warnings, fmt.Sprintf(
				"skill %q SKILL.md is %d bytes, exceeds max_result_chars (%d) — agent will see truncated instructions",
				s.Name, size, maxChars,
			))
		}
	}
	return warnings
}

// shortPath returns the shorter of absPath or its relative form from baseDir.
// If baseDir is empty or filepath.Rel fails, absPath is returned unchanged.
func shortPath(absPath, baseDir string) string {
	if baseDir == "" {
		return absPath
	}
	rel, err := filepath.Rel(baseDir, absPath)
	if err != nil {
		return absPath
	}
	if len(rel) < len(absPath) {
		// Prefix with "./" if the relative path doesn't already start
		// with "../", so it's visually clear it's a relative path.
		if !strings.HasPrefix(rel, "..") {
			rel = "./" + rel
		}
		return rel
	}
	return absPath
}

// parseSkillFile reads a SKILL.md and extracts frontmatter fields.
func parseSkillFile(path, dir string) (Skill, error) {
	f, err := os.Open(path)
	if err != nil {
		return Skill{}, err
	}
	defer func() { _ = f.Close() }()

	fm, err := parseFrontmatter(f)
	if err != nil {
		return Skill{}, err
	}

	name := fm["name"]
	if name == "" {
		return Skill{}, fmt.Errorf("missing required field: name")
	}

	skill := Skill{
		Name:          name,
		Description:   fm["description"],
		Command:       fm["command"],
		Autogenerated: parseBool(fm["autogenerated"]),
		Dir:           dir,
		Path:          path,
	}

	// Resolve script path relative to skill directory
	if fm["script"] != "" {
		skill.Script = filepath.Join(dir, fm["script"])
	}

	return skill, nil
}

// parseBool accepts the common truthy forms for a frontmatter scalar.
// Anything unrecognized (including empty) is false.
func parseBool(s string) bool {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "true", "yes", "1":
		return true
	}
	return false
}

// parseFrontmatter reads YAML frontmatter between --- markers.
// Returns a map of key: value pairs. Only handles simple scalar values.
func parseFrontmatter(f *os.File) (map[string]string, error) {
	scanner := bufio.NewScanner(f)

	// First line must be ---
	if !scanner.Scan() || strings.TrimSpace(scanner.Text()) != "---" {
		return nil, fmt.Errorf("no frontmatter")
	}

	fm := make(map[string]string)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimSpace(line) == "---" {
			return fm, nil
		}
		key, val, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		val = strings.TrimSpace(val)
		// Strip surrounding quotes
		val = strings.Trim(val, `"'`)
		if key != "" {
			fm[key] = val
		}
	}

	return nil, fmt.Errorf("unterminated frontmatter")
}
