package skills

import (
	"testing"
	"time"
)

func TestLogDeduperSuppressesUntilIntervalElapses(t *testing.T) {
	base := time.Unix(1_700_000_000, 0)
	cur := base
	d := &logDeduper{seen: make(map[string]time.Time), now: func() time.Time { return cur }}

	if !d.should("k") {
		t.Fatal("first call should log")
	}
	if d.should("k") {
		t.Fatal("immediate repeat should be suppressed")
	}

	cur = base.Add(skillLogInterval - time.Second)
	if d.should("k") {
		t.Fatal("just under the interval should still be suppressed")
	}

	cur = base.Add(skillLogInterval + time.Second)
	if !d.should("k") {
		t.Fatal("after the interval should log again")
	}
	if d.should("k") {
		t.Fatal("repeat right after re-logging should be suppressed")
	}

	if !d.should("other") {
		t.Fatal("a distinct key should log independently")
	}
}

func TestMergeIntoConsultsDeduper(t *testing.T) {
	saved := logDedup
	logDedup = newLogDeduper()
	t.Cleanup(func() { logDedup = saved })

	skills := []Skill{{Name: "x", Dir: "/d", Autogenerated: true}}
	mergeInto(&Registry{}, map[string]int{}, append([]Skill(nil), skills...))

	key := "/d\x00x\x00true"
	logDedup.mu.Lock()
	_, recorded := logDedup.seen[key]
	logDedup.mu.Unlock()
	if !recorded {
		t.Fatal("mergeInto should consult the deduper and record the skill's key")
	}
}
