package skills

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"foci/internal/log"
)

// captureSkillsLog routes log events to a buffer and gives the test a fresh
// dedup state, so a warning suppressed by an earlier test can't hide this one's.
func captureSkillsLog(t *testing.T) *bytes.Buffer {
	t.Helper()
	var buf bytes.Buffer
	log.SetOutput(&buf)
	t.Cleanup(func() { log.SetOutput(os.Stderr) })
	saved := logDedup
	logDedup = newLogDeduper()
	t.Cleanup(func() { logDedup = saved })
	return &buf
}

// TestLoadWarnsOnInvalidYAMLFrontmatter pins #2077: an unquoted ": " inside a
// description is invalid YAML that foci's line parser tolerates. Indexing must
// be unchanged (the skill still loads, same fields) but a WARN must name the
// file and the parse error, with the line number as it appears in the file.
func TestLoadWarnsOnInvalidYAMLFrontmatter(t *testing.T) {
	buf := captureSkillsLog(t)
	dir := t.TempDir()
	writeSkillMD(t, dir, "bad", "---\nname: bad\ndescription: Do things. Router: read the sub-file\n---\nbody\n")

	reg := Load([]string{dir})
	if reg.Len() != 1 {
		t.Fatalf("invalid YAML must not change indexing: got %d skills, want 1", reg.Len())
	}
	if got := reg.All()[0].Description; got != "Do things. Router: read the sub-file" {
		t.Errorf("description changed: %q", got)
	}

	out := buf.String()
	file := filepath.Join(dir, "bad", "SKILL.md")
	var warn string
	for _, l := range strings.Split(out, "\n") {
		if strings.Contains(l, "WARN") && strings.Contains(l, file) && strings.Contains(l, "not valid YAML") {
			warn = l
		}
	}
	if warn == "" {
		t.Fatalf("no YAML WARN naming %s; log:\n%s", file, out)
	}
	if !strings.Contains(warn, "line 3") {
		t.Errorf("warning should carry the file's line number (3): %s", warn)
	}
}

// TestLoadNoWarnOnValidYAMLFrontmatter is the negative arm: a quoted colon and
// plain scalar fields must not trip the check.
func TestLoadNoWarnOnValidYAMLFrontmatter(t *testing.T) {
	buf := captureSkillsLog(t)
	dir := t.TempDir()
	writeSkillMD(t, dir, "good", "---\nname: good\ndescription: \"Do things. Router: read the sub-file\"\nowner: foci\nautogenerated: false\n---\nbody\n")

	if reg := Load([]string{dir}); reg.Len() != 1 {
		t.Fatalf("got %d skills, want 1", reg.Len())
	}
	if strings.Contains(buf.String(), "not valid YAML") {
		t.Errorf("unexpected YAML warning for valid frontmatter:\n%s", buf.String())
	}
}
