package tools

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"net"
	"os"
	"strings"
	"sync"
	"sync/atomic"

	"foci/log"
)

// bridgeCounter provides unique socket paths across concurrent exec calls.
var bridgeCounter atomic.Int64

// ExecBridge creates a per-exec unix socket that exposes ExecExport tools
// as shell functions inside subprocess commands.
type ExecBridge struct {
	sockPath  string
	funcsPath string
	listener  net.Listener
	registry  *Registry
	ctx       context.Context
	cancel    context.CancelFunc
	wg        sync.WaitGroup
}

// NewExecBridge creates a unix socket and shell functions file. The bridge
// accepts connections until Close is called. ctx carries the session key
// from the calling agent (used by tools that need session identity).
func NewExecBridge(registry *Registry, ctx context.Context) (*ExecBridge, error) {
	n := bridgeCounter.Add(1)
	sockPath := fmt.Sprintf("/tmp/foci-exec-%d-%d.sock", os.Getpid(), n)
	funcsPath := fmt.Sprintf("/tmp/foci-exec-%d-%d-funcs.sh", os.Getpid(), n)

	listener, err := net.Listen("unix", sockPath)
	if err != nil {
		return nil, fmt.Errorf("exec bridge listen: %w", err)
	}
	// Restrict socket access
	if err := os.Chmod(sockPath, 0600); err != nil {
		listener.Close()
		os.Remove(sockPath)
		return nil, fmt.Errorf("exec bridge chmod: %w", err)
	}

	bridgeCtx, cancel := context.WithCancel(ctx)
	b := &ExecBridge{
		sockPath:  sockPath,
		funcsPath: funcsPath,
		listener:  listener,
		registry:  registry,
		ctx:       bridgeCtx,
		cancel:    cancel,
	}

	// Write shell functions file
	if err := b.writeShellFuncs(); err != nil {
		listener.Close()
		os.Remove(sockPath)
		cancel()
		return nil, fmt.Errorf("exec bridge write funcs: %w", err)
	}

	// Start accept loop
	b.wg.Add(1)
	go b.acceptLoop()

	log.Debugf("execbridge", "started sock=%s tools=%d", sockPath, b.exportedToolCount())
	return b, nil
}

// SockPath returns the unix socket path for FOCI_SOCK env var.
func (b *ExecBridge) SockPath() string { return b.sockPath }

// FuncsPath returns the shell functions file path.
func (b *ExecBridge) FuncsPath() string { return b.funcsPath }

// Close stops the listener, waits for in-flight connections, and removes files.
func (b *ExecBridge) Close() {
	b.cancel()
	b.listener.Close()
	b.wg.Wait()
	os.Remove(b.sockPath)
	os.Remove(b.funcsPath)
	log.Debugf("execbridge", "closed sock=%s", b.sockPath)
}

func (b *ExecBridge) acceptLoop() {
	defer b.wg.Done()
	for {
		conn, err := b.listener.Accept()
		if err != nil {
			// Expected when listener is closed
			return
		}
		b.wg.Add(1)
		go b.handleConn(conn)
	}
}

func (b *ExecBridge) handleConn(conn net.Conn) {
	defer b.wg.Done()
	defer conn.Close()

	scanner := bufio.NewScanner(conn)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	if !scanner.Scan() {
		return
	}

	var req struct {
		Tool   string          `json:"tool"`
		Params json.RawMessage `json:"params"`
	}
	if err := json.Unmarshal(scanner.Bytes(), &req); err != nil {
		writeResponse(conn, "", fmt.Sprintf("invalid request: %v", err))
		return
	}

	tool := b.registry.Get(req.Tool)
	if tool == nil {
		writeResponse(conn, "", fmt.Sprintf("unknown tool: %s", req.Tool))
		return
	}
	if !tool.ExecExport {
		writeResponse(conn, "", fmt.Sprintf("tool %s not exported for exec", req.Tool))
		return
	}

	log.Debugf("execbridge", "call tool=%s", req.Tool)
	result, err := tool.Execute(b.ctx, req.Params)
	if err != nil {
		writeResponse(conn, "", err.Error())
		return
	}

	// Strip HTTP headers from http_request results so piping works cleanly.
	// The tool returns "HTTP <status>\nHeader: val\n...\n\n<body>" — in a pipe
	// context only the body is useful (e.g. `foci_http_request url | jq .`).
	if req.Tool == "http_request" {
		result = stripHTTPHeaders(result)
	}

	writeResponse(conn, result, "")
}

func writeResponse(conn net.Conn, result, errMsg string) {
	resp := struct {
		Result string `json:"result,omitempty"`
		Error  string `json:"error,omitempty"`
	}{Result: result, Error: errMsg}
	data, _ := json.Marshal(resp)
	data = append(data, '\n')
	conn.Write(data)
}

// stripHTTPHeaders removes the HTTP status/header block from an http_request
// result, returning only the body. The format is "HTTP <status>\n...headers...\n\n<body>".
// If the separator isn't found, the result is returned unchanged.
func stripHTTPHeaders(result string) string {
	if idx := strings.Index(result, "\n\n"); idx >= 0 && strings.HasPrefix(result, "HTTP ") {
		return result[idx+2:]
	}
	return result
}

func (b *ExecBridge) exportedToolCount() int {
	count := 0
	for _, t := range b.registry.All() {
		if t.ExecExport {
			count++
		}
	}
	return count
}

// writeShellFuncs generates a bash file defining foci_<toolname>() for each
// exported tool. Functions use jq for safe JSON construction and foci-call
// for socket communication.
func (b *ExecBridge) writeShellFuncs() error {
	var sb strings.Builder
	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("# Auto-generated by foci exec bridge — do not edit\n\n")

	for _, t := range b.registry.All() {
		if !t.ExecExport {
			continue
		}
		fn := generateShellFunc(t)
		if fn != "" {
			sb.WriteString(fn)
			sb.WriteString(fmt.Sprintf("export -f foci_%s\n\n", t.Name))
		}
	}

	return os.WriteFile(b.funcsPath, []byte(sb.String()), 0600)
}

// generateShellFunc returns a bash function definition for a tool.
// Each tool gets a function named foci_<toolname> with appropriate argument handling.
func generateShellFunc(t *Tool) string {
	name := "foci_" + t.Name

	switch t.Name {
	case "web_search", "memory_search":
		// Simple query tools: all args become the query string
		return fmt.Sprintf(`%s() {
  local query="$*"
  if [ -z "$query" ]; then
    echo "usage: %s <query>" >&2
    return 1
  fi
  foci-call "$(jq -nc --arg q "$query" '{"tool":"%s","params":{"query":$q}}')"
}
`, name, name, t.Name)

	case "web_fetch":
		// URL as first arg, optional --raw flag
		return fmt.Sprintf(`%s() {
  local url="" raw=false
  while [ $# -gt 0 ]; do
    case "$1" in
      --raw) raw=true; shift ;;
      *) url="$1"; shift ;;
    esac
  done
  if [ -z "$url" ]; then
    echo "usage: %s <url> [--raw]" >&2
    return 1
  fi
  foci-call "$(jq -nc --arg u "$url" --argjson r "$raw" '{"tool":"web_fetch","params":{"url":$u,"raw":$r}}')"
}
`, name, name)

	case "http_request":
		// URL as first arg, flags for method, headers, body, save_to
		return fmt.Sprintf(`%s() {
  local url="" method="GET" body="" save_to="" headers="{}"
  while [ $# -gt 0 ]; do
    case "$1" in
      --method) method="$2"; shift 2 ;;
      --body) body="$2"; shift 2 ;;
      --header) headers="$(echo "$headers" | jq --arg k "${2%%%%:*}" --arg v "${2#*: }" '. + {($k): $v}')"; shift 2 ;;
      --save-to) save_to="$2"; shift 2 ;;
      *) url="$1"; shift ;;
    esac
  done
  if [ -z "$url" ]; then
    echo "usage: %s <url> [--method METHOD] [--header 'K: V'] [--body BODY] [--save-to PATH]" >&2
    return 1
  fi
  local params
  params="$(jq -nc --arg u "$url" --arg m "$method" --argjson h "$headers" '{"url":$u,"method":$m,"headers":$h}')"
  if [ -n "$body" ]; then
    params="$(echo "$params" | jq --arg b "$body" '. + {body: $b}')"
  fi
  if [ -n "$save_to" ]; then
    params="$(echo "$params" | jq --arg s "$save_to" '. + {save_to: $s}')"
  fi
  foci-call "$(jq -nc --argjson p "$params" '{"tool":"http_request","params":$p}')"
}
`, name, name)

	case "send_telegram":
		// Text as args or stdin; optional --file flag
		return fmt.Sprintf(`%s() {
  local text="" file_path="" send_as=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --file) file_path="$2"; shift 2 ;;
      --send-as) send_as="$2"; shift 2 ;;
      *) text="$text $1"; shift ;;
    esac
  done
  text="${text# }"
  if [ -z "$text" ] && [ -z "$file_path" ]; then
    if [ ! -t 0 ]; then
      text="$(cat)"
    fi
  fi
  if [ -z "$text" ] && [ -z "$file_path" ]; then
    echo "usage: %s <text> [--file PATH] [--send-as TYPE]" >&2
    echo "  or: echo 'message' | %s" >&2
    return 1
  fi
  local params="{}"
  if [ -n "$text" ]; then
    params="$(echo "$params" | jq --arg t "$text" '. + {text: $t}')"
  fi
  if [ -n "$file_path" ]; then
    params="$(echo "$params" | jq --arg f "$file_path" '. + {file_path: $f}')"
  fi
  if [ -n "$send_as" ]; then
    params="$(echo "$params" | jq --arg s "$send_as" '. + {send_as: $s}')"
  fi
  foci-call "$(jq -nc --argjson p "$params" '{"tool":"send_telegram","params":$p}')"
}
`, name, name, name)

	case "todo":
		// action as first arg, rest varies by action
		return fmt.Sprintf(`%s() {
  local action="$1"; shift 2>/dev/null || true
  case "$action" in
    add)
      local text="$*" priority="" tag=""
      foci-call "$(jq -nc --arg t "$text" '{"tool":"todo","params":{"action":"add","text":$t}}')"
      ;;
    list)
      foci-call '{"tool":"todo","params":{"action":"list"}}'
      ;;
    search)
      local query="$*"
      foci-call "$(jq -nc --arg q "$query" '{"tool":"todo","params":{"action":"search","query":$q}}')"
      ;;
    complete)
      local id="$1"
      foci-call "$(jq -nc --argjson id "$id" '{"tool":"todo","params":{"action":"complete","id":$id}}')"
      ;;
    remove)
      local id="$1"
      foci-call "$(jq -nc --argjson id "$id" '{"tool":"todo","params":{"action":"remove","id":$id}}')"
      ;;
    *)
      echo "usage: %s <add|list|search|complete|remove> [args...]" >&2
      return 1
      ;;
  esac
}
`, name, name)

	case "spawn":
		// prompt as args, optional --model and --context flags
		return fmt.Sprintf(`%s() {
  local prompt="" model="" ctx_mode=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --model) model="$2"; shift 2 ;;
      --context) ctx_mode="$2"; shift 2 ;;
      *) prompt="$prompt $1"; shift ;;
    esac
  done
  prompt="${prompt# }"
  if [ -z "$prompt" ]; then
    echo "usage: %s <prompt> [--model MODEL] [--context none|character_only|clone_current]" >&2
    return 1
  fi
  local params
  params="$(jq -nc --arg p "$prompt" '{"prompt":$p}')"
  if [ -n "$model" ]; then
    params="$(echo "$params" | jq --arg m "$model" '. + {model: $m}')"
  fi
  if [ -n "$ctx_mode" ]; then
    params="$(echo "$params" | jq --arg c "$ctx_mode" '. + {context: $c}')"
  fi
  foci-call "$(jq -nc --argjson p "$params" '{"tool":"spawn","params":$p}')"
}
`, name, name)

	default:
		// Generic: pass raw JSON
		return fmt.Sprintf(`%s() {
  foci-call "$(jq -nc --argjson p "$1" '{"tool":"%s","params":$p}')"
}
`, name, t.Name)
	}
}
